# Generated by Django 5.1.3 on 2024-12-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.language'),
        ),
        migrations.AlterField(
            model_name='work',
            name='difficulty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='api.type'),
        ),
    ]
