# Generated by Django 5.1.3 on 2024-12-03 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_work_language_alter_work_difficulty_alter_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user', to='api.work'),
        ),
    ]
