# Generated by Django 5.1.3 on 2024-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_current_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Link to the Amazon page for the work', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL for the cover image of the work', null=True),
        ),
    ]
